let events=[];let sources=[];let signals=[];let status={};let maxCost=20;let hideUnknown=false;let animalsOnly=false;
const ymd=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const nowLocal=new Date();const today=ymd(nowLocal);let cursor=new Date(nowLocal.getFullYear(),nowLocal.getMonth(),1,12);let selected=today;
const fmtDate=d=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(d);const fmtTime=iso=>iso?new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(iso)):'Time TBA';
const escapeHtml=(v='')=>String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));const cleanDescription=(v='')=>String(v).replace(/\\n/g,'\n').replace(/\r\n?/g,'\n').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim();
function allowed(e){if(animalsOnly&&!(e.categories||[]).includes('animals'))return false;if(e.cost==null)return !hideUnknown;return e.cost<=maxCost;}function occursOn(e,date){const s=String(e.start||'').slice(0,10),end=String(e.end||e.start||'').slice(0,10);return date>=s&&date<=end;}
function personalScore(e){let s=Number(e.score||5);const text=`${e.title||''} ${e.description||''} ${(e.perks||[]).join(' ')}`.toLowerCase();if(e.cost===0)s+=2.2;else if(e.cost!=null&&e.cost<=10)s+=1.1;else if(e.cost!=null&&e.cost<=20)s+=.3;if((e.categories||[]).includes('cars')||/car show|cars and coffee|cruise.?in|miata|autocross/.test(text))s+=3;if((e.categories||[]).includes('animals')||/animal|wildlife|aquarium|feeding|baby goat|birthday|debut|keeper/.test(text))s+=2.4;if(/free (food|beer|drink|wine)|complimentary|free admission|open house|festival|street stroll|art walk|guided tour|special event|once.?a.?year/.test(text))s+=1.8;if(/farmers.?market|toddler|business|networking|workshop|meeting|webinar/.test(text))s-=2.5;return s;}
function valueLabel(e){const s=personalScore(e);if(s>=10)return'🔥 GREAT FIND';if(s>=8)return'★ WORTH IT';return'';}function eventsOn(date){return events.filter(e=>occursOn(e,date)&&allowed(e)).sort((a,b)=>personalScore(b)-personalScore(a));}function monthEvents(){return events.filter(e=>{const d=new Date(e.start);return d.getFullYear()===cursor.getFullYear()&&d.getMonth()===cursor.getMonth()&&allowed(e);}).sort((a,b)=>personalScore(b)-personalScore(a));}
function eventIndicator(ev){if(!ev.length)return'';const dots=ev.slice(0,4).map(e=>`<span class="event-dot ${(e.categories||[]).includes('animals')?'animal':e.cost===0?'free':'cheap'}"></span>`).join('');return `<div class="event-indicator"><span class="event-dots">${dots}</span><span class="event-count">${ev.length}<span class="event-count-label"> event${ev.length===1?'':'s'}</span></span></div>`;}
function renderCalendar(){document.getElementById('monthLabel').textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(cursor);const cal=document.getElementById('calendar');cal.innerHTML='';const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),gridStart=new Date(first);gridStart.setDate(1-first.getDay());for(let i=0;i<42;i++){const d=new Date(gridStart);d.setDate(gridStart.getDate()+i);const key=ymd(d),ev=eventsOn(key),cell=document.createElement('div');cell.className='day'+(d.getMonth()!==cursor.getMonth()?' outside':'')+(key===selected?' selected':'')+(key===today?' today':'')+(ev.length?' has-events':'')+(ev.some(x=>(x.categories||[]).includes('animals'))?' animal-day':'');const previews=ev.slice(0,2).map(x=>`<div class="mini-event ${(x.categories||[]).includes('animals')?'animal':''}">${escapeHtml(x.title)}</div>`).join('');cell.innerHTML=`<span class="num">${d.getDate()}</span><div class="day-events">${previews}</div>${eventIndicator(ev)}`;cell.onclick=()=>{selected=key;render();};cal.appendChild(cell);}}
function badges(e){const out=[];const value=valueLabel(e);if(value)out.push(`<span class="badge value">${value}</span>`);if(e.cost===0)out.push('<span class="badge free">FREE</span>');if((e.categories||[]).includes('animals'))out.push('<span class="badge animal">🐾 ANIMAL</span>');if((e.categories||[]).includes('cars'))out.push('<span class="badge car">CAR EVENT</span>');return out.join('');}
function descriptionBlock(e,index){const text=cleanDescription(e.description||'');if(!text)return'';const expandable=text.length>260||text.includes('\n');return `<div class="description-wrap"><p class="description${expandable?' collapsible':''}" id="description-${index}">${escapeHtml(text)}</p>${expandable?`<button class="description-toggle" data-target="description-${index}">Show full description</button>`:''}</div>`;}function wireDescriptionToggles(){document.querySelectorAll('.description-toggle').forEach(btn=>btn.onclick=()=>{const t=document.getElementById(btn.dataset.target);const expanded=t.classList.toggle('expanded');btn.textContent=expanded?'Collapse description':'Show full description';});}
function renderList(all=false){const list=document.getElementById('eventList'),chosen=all?monthEvents():eventsOn(selected);document.getElementById('selectedDate').textContent=all?'Best bets · '+new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(cursor):fmtDate(new Date(`${selected}T12:00:00`));if(!chosen.length){list.innerHTML='<div class="empty">Nothing worth showing here yet.</div>';return;}list.innerHTML=chosen.map((e,index)=>{const links=(e.sources||[]).map(s=>`<a target="_blank" rel="noreferrer" href="${escapeHtml(s.url||'')}">${escapeHtml(s.name||'Source')}</a>`).join(' · '),time=e.allDay?'Times vary':(e.end?`${fmtTime(e.start)}–${fmtTime(e.end)}`:fmtTime(e.start));return `<article class="card"><div class="card-top"><div><h3>${escapeHtml(e.title)}</h3><div class="meta">${time}<br>${escapeHtml(e.location||'Location TBA')}<br><strong>${escapeHtml(e.costLabel||'Price unknown')}</strong></div></div><div class="score">${personalScore(e).toFixed(1)}</div></div><div class="badges">${badges(e)}</div>${descriptionBlock(e,index)}<div class="sources">Source: ${links||'Auto-discovery'}</div></article>`;}).join('');wireDescriptionToggles();}
function renderSummary(){const free=events.filter(e=>e.cost===0).length,good=events.filter(e=>personalScore(e)>=8).length;document.getElementById('summary').innerHTML=`<strong>${good}</strong> worth-a-look finds · <strong>${free}</strong> free<br><span>${events.length} current events indexed</span>`;}function renderSignals(){const target=document.getElementById('animalSignals'),rows=signals.filter(s=>s.kind==='animal-watch').slice(0,5);target.innerHTML=rows.length?rows.map(s=>`<article class="signal"><div class="signal-title">${escapeHtml(s.title)}</div><p>${escapeHtml(cleanDescription(s.excerpt))}</p><a target="_blank" rel="noreferrer" href="${escapeHtml(s.url)}">Open source →</a></article>`).join(''):'<div class="import-empty">No fresh animal leads right now.</div>';}
function renderHealth(){const target=document.getElementById('sourceHealth');if(!target)return;const healthy=sources.filter(s=>s.health&&s.health.status==='ok').length;target.innerHTML=`<div class="health-summary">${healthy}/${sources.filter(s=>s.url).length} sources checked successfully. Technical details intentionally tucked away.</div>`;}
function render(){renderCalendar();renderList(false);renderSummary();renderSignals();renderHealth();}async function loadData(){try{const [er,sr,gr,tr]=await Promise.all([fetch('/api/events',{cache:'no-store'}),fetch('/api/sources',{cache:'no-store'}),fetch('/api/signals',{cache:'no-store'}),fetch('/api/status',{cache:'no-store'})]);events=await er.json();sources=await sr.json();signals=await gr.json();status=await tr.json();render();}catch(err){document.getElementById('eventList').innerHTML=`<div class="error">Could not load events: ${escapeHtml(err.message)}</div>`;}}
document.getElementById('prevMonth').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1,12);selected=ymd(cursor);render();};document.getElementById('nextMonth').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1,12);selected=ymd(cursor);render();};document.getElementById('todayBtn').onclick=()=>{const d=new Date();cursor=new Date(d.getFullYear(),d.getMonth(),1,12);selected=ymd(d);render();};document.getElementById('showAll').onclick=()=>renderList(true);document.querySelectorAll('input[name="cost"]').forEach(r=>r.onchange=e=>{maxCost=Number(e.target.value);render();});document.getElementById('hideUnknown').onchange=e=>{hideUnknown=e.target.checked;render();};document.getElementById('animalsOnly').onchange=e=>{animalsOnly=e.target.checked;render();};document.getElementById('runDiscovery').onclick=async e=>{const btn=e.currentTarget;btn.disabled=true;btn.textContent='Searching…';try{await fetch('/api/discovery/run',{method:'POST'});await loadData();btn.textContent='Updated';setTimeout(()=>btn.textContent='Search now',1800);}finally{btn.disabled=false;}};loadData();setInterval(loadData,60000);
